# Running 'conda env create' in this directory will install necessary dependencies
name: pdNLS

channels:
  - mlgill

dependencies:
  - notebook>=4.2.1
  - matplotlib>=1.5.1
  - numpy>=1.11.1
  - pandas>=0.18.1
  - seaborn>=0.7.0
  - multiprocess>=0.70.4
  - lmfit>=0.9.3

